### ISSUE TITLE
clean out copypasta from starter repo

### ISSUE THREAD

**Issue by fabian-s** [teaching-data-science/intro2ml#8] opened 2020-06-24 12:05 UTC
lots of stuff left over from the starter repo template -- let's get rid of that, link to it where appropriate, and include info relevant for *this* repo and *our* workflow instead, see e.g. #6 #3

**Comment by OmidCharrakh** [comment] 2020-07-23 20:33
I think the problem is resolved now because I transferred the main changes to the master branch.

**Closed as completed by OmidCharrakh** 2020-07-23 20:33 UTC
